FEET_KEY = 'feet'
INCHES_KEY = 'inches'
DECLINED_LOW_WEIGHT = 'Declined_low_weight'
LAST_MODIFIED_CACHE_KEY = 'last_modified'
LOW_WEIGHT_MESSAGE = 'weight is too low'
HIGH_WEIGHT_MESSAGE = 'weight is too high'
COVERAGE_ILLEGAL_MESSAGE = 'coverage amount illegal'
ILLEGAL_AGE_MESSAGE = 'age illegal'
ILLEGAL_TERM_MESSAGE = 'term illegal'
ILLEGAL_COMBINATION_MESSAGE = 'combination between age and term illegal'
ILLEGAL_HEIGHT_MESSAGE = 'Height illegal'

RANGE_FIELD_REGEX = '\$(\d+\s?[kKmMbB]?) - \$(\d+\s?[kKmMbB]?)'
LIMIT_REGEX = '^(\d+)\s?([kKmMbB])$'

DECLINED_STATUS = 'Declined'
